import type { Metadata } from "next";
import { Roboto } from 'next/font/google';
import "./globals.css";
import { ThemeProvider } from "@/components/Providers/ThemeProvider";
import Header from "@/components/shared/Header/Header";
import Footer from "@/components/shared/Footer/Footer";
import Providers from "@/lib/providers/Providers";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  display: 'swap',
});



export const metadata: Metadata = {
  title: "Juri Link",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head> <link rel="icon" type="image/png" href="/logo9.png" /></head>
      <body
        className={`${roboto.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <div>
            <ToastContainer position="top-right" autoClose={3000}/>   
              <Header></Header>
              {children}
              <Footer></Footer>
            </div>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
